### ISSUE TITLE
Problem with getting and processing with the raw video data.

### ISSUE THREAD

**Issue by cenjinglun** [cwi-dis/CEAP-360VR-Dataset#2]
Hello, I have downloaded 8 videos using `youtube_dl` according to the method mentioned in your paper, but I can't find any information about cutting the videos into segments(60s), can you tell me more details about it?

**Comment by luisqtr** [comment]
Hi have just created a pull request with a copy of the videos and a notebook that crops the videos using OpenCV. You can check it on [my branch](https://github.com/luisqtr/CEAP-360VR-Dataset) or wait until CWI merges the PR.
